name: Node.js CI

on:
  push:
    branches: [ master ]  # Use master because your branch is master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build check
      run: echo "✅ Build complete"
